### ISSUE TITLE
TFLite parser: failed to CreateNetworkFromBinaryFile with squeeznet.tflite and inceptionv3.tflite

### ISSUE THREAD

**Issue by vinceab** [ARM-software/armnn#393]
Both inceptionv3.tflite and squeeznet.tflite models are floating point models and come from:
https://www.tensorflow.org/lite/guide/hosted_models

The following code:
armnnTfLiteParser::ITfLiteParserPtr parser = armnnTfLiteParser::ITfLiteParser::Create();
armnn::INetworkPtr network = parser->CreateNetworkFromBinaryFile("squeeznet.tflite");

Leads to the following issue:
terminate called after throwing an instance of 'armnn::ParseException'
  what():  Buffer #32 has 0 bytes. For tensor: [1,1001] expecting: 4004 bytes and 1001 elements.  at function CreateConstTensor

Using inceptionv3.tflite instead of squeeznet.tflite does not output any error but CreateNetworkFromBinaryFile function is never ending.

**Comment by Colm-in-Arm** [comment]
Hi Vincent,

Can you tell me what target environment and which version of ArmNN you were using please. I'll try and recreate on x86_64 with ArmNN master today.

Colm.

**Comment by vinceab** [comment]
Hi Colm,

I am using armnn 20.05 on a arm 32bits system STM32MP1 dual cortexA7.

Vincent

**Comment by Colm-in-Arm** [comment]
I just spotted we have a plan to fix the difference in shape handling between Android NDK and TF.

**Comment by Colm-in-Arm** [comment]
Hi Vincent,

I've managed to recreate both problems on v7 32bit. It occurs on both 20.05 and on master. I'll start investigating next week.

Colm.

**Comment by Colm-in-Arm** [comment]
Hi Vincent,

There's good news and bad...

I've fixed the exception handling in the TfLiteParser so now the squeeznet.tflite fails gracefully. This is the [commit on master](https://github.com/ARM-software/armnn/commit/6350d27286114dfdae5f65ae1823ba1150087efb). 

It still means that this model fails because the format of the Reshape parameter is unsupported. There is an open bug that @TeresaARM reported. It is highly likely to be fixed before the 20.08 release.

There's also a solution for inceptionv3.tflite: time. I ran it on a Raspberry Pi 3B+ and it took 7m22.207s. I didn't check the accuracy but it did complete without errors. Of the total time, inference took 99.09% of it. Does the length of execution cause a problem on your system?

Colm.

**Comment by vinceab** [comment]
Hi Colm,

I confirm that inceptionv3 is running fine.
It was actually a RAM issue. I did not have enough RAM with the STM32MP157C-DK2 board (with 512MB of RAM).
I move to the STM32MP157C-EV1 (with 1GB of RAM) and the model is running fine.

So only the squeeznet is finaly having trouble.

Thanks
Vincent

**Comment by james-conroy-arm** [comment]
Hi @vinceab ,

Are you still experiencing issues with the SqueezeNet model?

Cheers,
James

**Comment by vinceab** [comment]
The fix mention by colm avoid the application to crash  that's a good point but the Squeeznet is still not supported.

**Comment by janeil01** [comment]
Hi @vinceab,

I just added a [patch to master](https://github.com/ARM-software/armnn/commit/bac9b35df7c59f6b5b61e1d233a49bdb88a973ba) that should fix the issue in the Reshape operation. @Colm-in-Arm mentioned you had a problem with that when running squeezenet.
You could give that a go and see if you can execute squeezenet with it :)

Good luck
Jan

**Comment by vinceab** [comment]
Hi Jan,

I have verified the patch and squeeznet is now running successfully.

Thank you
Vincent
